### ISSUE TITLE
dont' detect duplicate names

### ISSUE THREAD

**Issue by Kikobeats** [andismith/grunt-responsive-images#34]
if you run responsive_images task and later run the some taks for copy the new images....

![image](http://i.imgur.com/ldjVErJ.png)

generate moar images

my task:

```
responsive_images:
  options:
    engine: "gm"
    separator: ""
    sizes: [
      name: "@2x"
      width: '200%'
    ]
  files:
    expand: true
    cwd: "<%=conf.dest_assets%>/img/"
    src: ["**/*.{jpg,gif,png}"]
    dest: "<%=conf.dest_assets%>/img/"
```

I don't use suffix becase is broken
